#!/bin/bash

VAR_TV=/var/TV
. $VAR_TV/.env_var_TV

LOG1=/tmp/get_iPlayer.log

cd /var/TV/
cd $VAR_TV/PVR/
PATH=/var/TV/:$VAR_TV/get_iplayer:$PATH

get_iplayer.cgi \
-g $VAR_TV/get_iplayer/get_iplayer \
-p 1935 \
# 2>&1 | tee -a $LOG1
#
