#! /bin/bash

# run from cron -e exits on first error (false) +e stays
set +e

VAR_TV=/var/TV
. $VAR_TV/.env_var_TV
# that did a cd ~/G/PVR/
(
	date
	pwd

	for fullname in *_-_*
	do
		[ -f "$fullname" ] || continue
		if f=`expr match "$fullname" '\(.*\)_-_...'`
		then
			echo "# OK # $f # $fullname"
			[ -d $f ] || mkdir $f
			mv "$fullname" "$f"
		else
			echo "# FAIL # - # $fullname"
		fi
	done

 # check the lock file has an oner


) 2>&1 | tee -a $LOG1.list.txt

	# --metadata-only \
